### ISSUE TITLE
Strange Fill Warp behaviour add foreground color to fill screen.

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#103]
Using the central colorfull dots pattern as a brush (see pic) :
![image](https://github.com/mriale/PyDPainter/assets/130657737/1ddfbcff-3e89-40ea-a74b-13f84a9338a5)

Use this brush as **Wrap filling** option in tools like **square** or **circle** to produce the figure on the right of my example. Works fine.

Now use simple **Fill tool** to fill the screen. A new color appears in the filling, mostly the current foreground color. 
![image](https://github.com/mriale/PyDPainter/assets/130657737/0132904f-d88d-4ef3-a37a-218dbba90136)

This is a incorrect behaviour for this tool.
(1.2.2 release)

**Comment by mriale** [comment]
Thanks for finding that! I vaguely remember seeing this once and forgot about it. Now after it does the flood fill it restores the picture before it renders the fill mode.
