### ISSUE TITLE
Display RGB value on palette tooltip

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#106]
When the mouse is hovering over the palette in the lower-right corner of the screen, display the RGB value of the color under the cursor in the tooltip.

**Comment by mriale** [comment]
The last line is what was added to the tip with the color index and RGB values in hex and decimal:
![image](https://github.com/mriale/PyDPainter/assets/26576606/6f56da5f-96f2-4457-a747-03ce5c7f5cb0)

**Comment by mriale** [comment]
@WayneAshworth Just wanted to let you know that this feature is in the develop branch and will be rolled into PyDPainter 2.0.0. Thanks for giving me this idea!
![image](https://github.com/mriale/PyDPainter/assets/26576606/7d400751-b297-4140-869e-c01198f8c826)
![image](https://github.com/mriale/PyDPainter/assets/26576606/5dbaf530-1b07-4b28-b1c2-86a616cb0456)

**Comment by WayneAshworth** [comment]
That is so cool!! :D :D
I am so glad! At-a-glance stuff is so helpful 

I have tons of ideas really, my head is always full of them. I have been working in PyDPainter this morning, is so good.
