### ISSUE TITLE
Next frame / Previous frame shortcut display (tooltip)

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#108]
Tool tips don't display on nav bar.
Moving to next / previous frame while drawing is easier with '1'  '2' key but it don't show.

**Comment by mriale** [comment]
I had to change the tips on the anim toolbar to render on the right side since it was too close to the left edge of the screen.

**Comment by Sleuthgame** [comment]
Everything work fine. Nice shortcuts BTW.
