### ISSUE TITLE
F10 hide/show toolbar cycle

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#109]
F10 is 👍 
but it lack a state where the anim navbar is only here without toolbar. Very usefull while drawing a full screen animation.

**Comment by Sleuthgame** [comment]
Default : all toolbars
F10 once : anim navbar is hidden
F10 again : toolbar is hidden
Maybe :
F10 again : navbar is back without toolbar (when drawing an animation frame by frame, it's quite good.
Deluxe Paint use to have F9 for menu bar, it was usefull because it display current mode and coordinates.

**Comment by mriale** [comment]
When in single image mode, the states are:
- toolbar and menu bar on
- canvas only

When in animation playing mode, the states are:
- anim toolbar on
- canvas only

Animation mode now has 5 states:
- toolbar, menu bar, anim toolbar
![Screenshot at 2024-01-28 20-05-57](https://github.com/mriale/PyDPainter/assets/26576606/4b380ecd-7ade-4092-9c8a-840205489684)
- toolbar, menu bar
![Screenshot at 2024-01-28 20-06-07](https://github.com/mriale/PyDPainter/assets/26576606/5c3da172-731f-4b1e-835a-01f0e705c0f5)
- menu bar
![Screenshot at 2024-01-28 20-06-14](https://github.com/mriale/PyDPainter/assets/26576606/e9bb4aad-68c2-4465-bb12-5376397b0bc2)
- anim toolbar
![Screenshot at 2024-01-28 20-06-24](https://github.com/mriale/PyDPainter/assets/26576606/77c43703-67a5-4840-a801-c14ad9c9a283)
- canvas only
![Screenshot at 2024-01-28 20-05-49](https://github.com/mriale/PyDPainter/assets/26576606/e92127eb-1390-4c83-914f-d069cf9a8569)

**Comment by Sleuthgame** [comment]
It's working.

I'm not convinced, because personally I'd like the menu bar and nav toolbar when I draw an animation. Having a reminder of the current mode is vital, and the dimensions of the shapes is super handy too.

Sorry about that,

**Comment by mriale** [comment]
Hmmm... since I've already added overscan support, I think I could find a way to make the toolbars and menus outside of the drawing canvas. Added issue #116.

**Comment by Sleuthgame** [comment]
That's an elegant solution ! I like it ! Sound so obvious after you say it.
Not so easy to rethink UX while making a lecacy tool.
