### ISSUE TITLE
Won't save gif without a .gif

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#110]
Anim save... don't save anim if you dont type toto.gif as a filename. If you type just toto, it does not save. User has to type .gif. And guess it's GIF.

**Comment by Sleuthgame** [comment]
![boing1](https://github.com/mriale/PyDPainter/assets/130657737/6adefefb-de34-4ccf-b5fc-427f2e6445bc)

**Comment by mriale** [comment]
Added file type drop-down in commit a41c373.

Defaults to ANIM file if no file type is specified.
