### ISSUE TITLE
Anim Copy to all frames triger a mode

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#111]
I encountered a useful but unexpecting behaviour. Seems to me that "Copy to all" is working like expected but triggers some "Draw on all frames" mode. Is that possible ?
What ever I draw is now automatically on all frames.
Very useful ! but I can't figure how to stop it. :-)

1. Set # to 10.
2. Draw a ball or something on frame 1.
3. Jump to frame 2, it's blank, okay ?
4. Go back to frame 1. 
5. Use menu Anim/Frames/Copy to all. Ball from frame 1 is now everywhere, fine.
6. Draw something new.
7. Go to next frames. My God, it's drawn on all frames ! Whatever you draw is cloned on every frame. Maybe usefull ! 
But it can't stop.

**Comment by Sleuthgame** [comment]
I don't know if it was expected, but a "Draw on every frame" toogle is certainly very useful. I don't remember this, but I was never a Animator on DPaint (I use 3D or SCALA).

**Comment by mriale** [comment]
Ooops! No that was not intended. Thanks for finding that.

**Comment by Sleuthgame** [comment]
Bug as a feature. 😺 
Is there a chance to redo that as a feature ? 🙄
