### ISSUE TITLE
Documentation for animation features

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#113]
- Anim menu
- Quick reference card
- Other things?

**Comment by Sleuthgame** [comment]
- Beginner tutorial.

 I have something quick and easy in mind.

**Comment by Sleuthgame** [comment]
Oh yeah,a quick reference about the new nav bar, I get it now.
I will be a little busy until 25 of febuary. Maybe I should prioritize about the main md doc.

**Comment by Sleuthgame** [comment]
I have done months ago, a .afphoto affinity file for this new nav/anim bar (here as png). Are you done with this part ? I can update it with the new PALETTE icon and finish it during this summer.
<img width="596" alt="hotkeys-animtoolbar" src="https://github.com/mriale/PyDPainter/assets/130657737/457331d5-0d6f-46fc-93e1-cf2aa3181f2d">

Anim.md was already done, but I guess there are lot of existing features (stencils, background, merge, CLR) that where updated for animation.

How do you think we can handle this ?

1. Update all tools where they actually are ? 
2. Create a new Anim structure: anim navbar, anim menu, palette and animrate, future moverequester, and a new page for all new animations fixs impacting others tools.

(1) Sound complicated to maintain with a lot of files to edit. Messing default behaviour with the new one with frames.

**Comment by Sleuthgame** [comment]
My existing anim.md from the menu.

[anim.md](https://github.com/user-attachments/files/16095685/anim.md)

**Comment by mriale** [comment]
I updated the palette image and linked this into the Table of Contents.

**Comment by mriale** [comment]
I think the anim documentation is at a good point for the 2.0 release.
