### ISSUE TITLE
Hello! A question and request for PyDPainter.

### ISSUE THREAD

**Issue by MetalMaxMX** [mriale/PyDPainter#126]
Hello,

I am working on adding PyDPainter to the [Free Software Directory][0]. 
However, before it can be approved the entry requires copyright 
information. Would you mind adding a copyright notice in the README file 
or better yet as a file header for all the files?

[0]: https://directory.fsf.org/wiki/PyDPainter

I also see in PyDPainter-1.2.2/libs/menureq.py that PyDPainter might be 
GPLv3-or-later. Is it your intention to license PyDPainter under the 
GPLv3-or-later? If so would you mind putting a declaration in the README 
file? This would allow recipients to know that it is GPLv3-or-later 
without having to run the program or look at the [menereg.py](http://menereg.py/) file.

Thank you for making free software.

Cheers!
MetalMaxMX.

**Comment by mriale** [comment]
@MetalMaxMX I think by putting the GPLv3 in the LICENSE file in the root, it tagged the whole PyDPainter repository as GPLv3. It least that's the impression I got when I set it up. It looks like mmzero already verified it as GPLv3 on the FSF Directory. Does that mean it's good without changes?

Thank you for helping to get PyDPainter out to more people!

**Comment by mriale** [comment]
Oh, I know you were interested in animation, and I don't know if you've been looking at animation features in the `develop` branch, but they are coming along nicely. I'm trying to get a bit more functionality built up before I do another release, though. I wrote my reasons here: https://pydpainter.blogspot.com/2024/02/animation-debugging-for-fun-and-profit.html

**Comment by MetalMaxMX** [comment]
> @MetalMaxMX I think by putting the GPLv3 in the LICENSE file in the root, it tagged the whole PyDPainter repository as GPLv3. It least that's the impression I got when I set it up. It looks like mmzero already verified it as GPLv3 on the FSF Directory. Does that mean it's good without changes?
> 
> Thank you for helping to get PyDPainter out to more people!

Hello! Thank you for your answer. This is about the copyright information of the program. Y'know, like "Written by X, Copyright by Y in Year Z to A" anywhere on the readme, in your case it would be something like "PyDPainter was written by Mark Riale, Copyright © 2023-2024" (Or at least, that's how I understand it. I am pretty new to this still), the about screen of your application shows something similar to that but it would be easier to verify this on the README.md as it's easier for other contributors to check on it. (The GPLv3 license itself suggests doing this as     <program>  Copyright (C) <year>  <name of author>, so it could be PyDPainter Copyright (C) 2023-2024 Mark Riale too)

We wanted clarification on which GPLv3 are you using, because usually it's either GPLv3 or later or GPLv3 only. Since you already stated your intentions of having GPLv3 or later (menureq.py), we would like you to put it somewhere easier to read. Like "This program is licensed under the GPLv3 or later, check LICENSE" under the README.md and that would solve the issue neatly. 

Many thanks for answering!  And yeah, I keep promoting PyDPainter whenever possible, it's a cool app :)



> Oh, I know you were interested in animation, and I don't know if you've been looking at animation features in the `develop` branch, but they are coming along nicely. I'm trying to get a bit more functionality built up before I do another release, though. I wrote my reasons here: https://pydpainter.blogspot.com/2024/02/animation-debugging-for-fun-and-profit.html

Hey, I checked your blogpost and it's nice that you keep working on that! Yeah, I am particularly looking at the animation features since PixelJoint really likes it when a pixel-art application does have animation support built-in. I am eagerly awaiting for 2.0 and I even update the develop repository once in awhile to take a look at how the whole picture is shaping, exciting times ahead!

**Comment by mriale** [comment]
I added this to the bottom of README.md:

**PyDPainter Copyright (C) 2019-2024 Mark Riale**
This program is licensed under the GPLv3 or later. See LICENSE file for more details.

Does that work?

**Comment by MetalMaxMX** [comment]
I think that works just fine! Seems like it is enough for the program to be accepted into the directory. 

However, I would like to leave this issue open as the FSF directory-meeting is scheduled for next Friday on IRC. In case they need anything more or the like and I'd like to ask them here. In case they don't, I'll mention the VERIFIED added program on the issue and that you're free to close this. Thanks for your understanding!

**Comment by MetalMaxMX** [comment]
Good news! It has been approved and is out here at: https://directory.fsf.org/wiki?title=PyDPainter

Good job and thanks for answering my queries so that this effort could happen. Feel free to close the issue!

**Comment by mriale** [comment]
@MetalMaxMX Glad it was approved. Thanks for submitting this! Now more people can find PyDPainter.
