### ISSUE TITLE
Erractic Screen change on anim

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#132]
Load [https://www.randelshofer.ch/animations/anims/byte_by_byte/F-15.anim.html](https://www.randelshofer.ch/animations/anims/byte_by_byte/F-15.anim.html) as anim.
Change Screen format to 8 colors.
Play Animation
Hit Palette
Screen palette display is back to 2 colors or erratic behaviour began until crash.

**Comment by mriale** [comment]
Added support for animation to the following:
- Picture/Screen Format
- Picture/Page Size

These menu items allow you to change these attributes for all the frames of an animation:
- screen mode
- resolution
- number of colors

It shows the frames as they are processing and has a progress bar.

I also added a button to the Color Keyframes requestor to allow you to set a global color palette for the entire animation.

By using these two features together, you can reduce the number of colors in an animation and then pick a global palette for the animation.

**Comment by Sleuthgame** [comment]
Great job ! 
Can't wait to test thoses new features.

**Comment by Sleuthgame** [comment]
Works great ! Anim5 upgraded to 16 colors, added a landscape with a background merge, saved as GIF.
![F-15-fd](https://github.com/mriale/PyDPainter/assets/130657737/b2ff25ab-c02a-496d-98f0-fef1b7669db0)
