### ISSUE TITLE
Hidden functions of DPaint III not implemented

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#139]
By digging into the Dpaint III documentation, I found various advanced "hidden" functions (often with a key) that seem very useful.
They're not well known, so I don't think anyone has thought to point them out or reproduce them.

**FILL TOOL**
Holding down the **Alt key** when you click with the Fill cursor, fills outward to the background color. In other words, the fill spreads
outward until it reaches areas of the current background color. This works well in combination with the Tint fill setting to change the  color of a gradient. _(that's a banger !)_ 💯 

**FILLED FREEHAND SHAPE TOOL**
Holding down the **Alt key** as you click on the Filled Freehand Shape tool causes the tool to paint shapes that are filled and then outlined with the current brush using the settings of the Spacing requester. If you use a custom brush as your current brush, it is possible to paint shapes that are filled with one color and outlined with another. The outline is painted by tracing the shape with the current brush. Note that the shape is traced by the brush handle; if the handle is offset from the brush, the outline will be offset from your filled shape.
_(Waouh ! Never heard of that)_

**CURVE TOOL**
Holding down the **Ctrl** key as you paint a curve, causes the curve to leave "traces" as you paint.
_Ellipse and polygons also had this option, although I wonder at what point, given the way they were drawn. We'd have to check on the real DPaint program._

**BRUSH SELECTOR**
Holding down the **Shift key** while selecting a brush with the rectangular Brush Selector will constrain the brush to be a square. This means that it will be the same number of pixels high as it is wide. Because the pixels of the Amiga display are not square, your brush may not appear square. If you want the brush to appear square, tum on the Be Square option in the Prefs menu before you select the brush.
_This is a very useful function for sprite sheets in games. I remember it very well and it's the same for rectangles._

**Comment by mriale** [comment]
This is a great collection of stuff I forgot about or didn't get to. Thanks for including these for the sake of completion.

I did just add the Curve Ctrl key traces in d2f5e2f16dcebfb7b6f58374d6d52d592234c02c.

**Comment by Sleuthgame** [comment]
I know we have a selective memory, but these functions triggered by ALT are either totally unknown to me or I've forgotten them.

Thanks for the Curve trace. I'll check out.

**Comment by Sleuthgame** [comment]
It's good for the last two and it's documented.

**Comment by MetinSeven** [comment]
Good points. I remember a few of these from my DPaint days. 💚

**Comment by mriale** [comment]
ALT-fill is working now. I don't think I ever used back in the day. Now if only I had the tint fill mode working!

**Comment by Sleuthgame** [comment]
It works great! Super useful.

**Comment by Sleuthgame** [comment]
Doc is updated.

**Comment by mriale** [comment]
Added an outline when ALT-clicking on the Filled Freehand tool. Looks interesting:
![image](https://github.com/user-attachments/assets/211e3cab-125a-4562-b01c-70c1c4e77918)

I had misread the description the first few times. I was pressing ALT while drawing and not seeing any effect in DPaint III. Later I re-read the description and saw that it it said to ALT-click on Filled Freehand tool. I duplicated this functionality in PyDPainter. I also added it to the tool tip.

**Comment by Sleuthgame** [comment]
I was also surprised to see that **ALT** changes the behavior of a tool when you select it. I don't think that's very DPaint-like behavior. I'd also have preferred ALT when drawing.

It's like ALT on FILL, it's more coherent.

**Comment by Sleuthgame** [comment]
Does it also include the current brush and stroke attributes, or is it too complex?
A little more and you've got Illustrator for pixel. ;-)

**Comment by mriale** [comment]
The current brush/stroke attributes are maintained:
![image](https://github.com/user-attachments/assets/44fed403-fa50-4f46-ac6d-cda075146517)

However, color cycling or every nth dot don't look that great since it draws a line for each point in the polygon, and modern systems are so fast that the points are very close to each other. You have to draw really fast for it to to make an interesting border. But that's the way it is on DPaint III on an emulated A4000 as well.

**Comment by mriale** [comment]
Also added CTRL traces for the ellipse tool.

**Comment by Sleuthgame** [comment]
Watch this ! I found a way of using it.

![image](https://github.com/user-attachments/assets/ae2c13a7-1469-449a-bd9f-e2d447842fbe)

**Comment by Sleuthgame** [comment]
> Also added CTRL traces for the ellipse tool.

OMG ! Thanks you !
![image](https://github.com/user-attachments/assets/efc47d0d-b09e-4322-9df7-12096d4af6a3)

**Comment by Sleuthgame** [comment]
![elipse-trace](https://github.com/user-attachments/assets/64eef7ae-8162-41f8-8f7f-a4335dd25953)

**Comment by Sleuthgame** [comment]
I'm updating the tollobox.md file with illustrations.

![image](https://github.com/user-attachments/assets/34234a55-cb8d-4a43-820d-603f5b5f6bdd)
