### ISSUE TITLE
Implement Animpainting

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#146]
Hold the Windows or Mac Meta key to advance animation frames while painting.

**Comment by mriale** [comment]
Animpainting works for all dot and line-based tools (except airbrush). It also automatically adjusts to the number of frames if you have the spacing option set to continuous.

To activate, hold down the Left-Windows key or the Left-Command key on the Mac before you drag out a line or draw with a tool. When you let go of the mouse button, the brush will be stamped on successive frames.

I'm not sure if this works like the DPaint III version because I can't get the Amiga key to work right on my laptop keyboard.

**Comment by Sleuthgame** [comment]
YES ! It works. It pop up the Windows menu at the end, but I'll check how to unactivate that.
Please include my iff files:
cherckerboard.iff
redball.iff
blueball.iff
for future tutorials and explanations.

**Comment by Sleuthgame** [comment]
It works, but the windows menu is poping on at the very end. It's hard not to trigger it.
I try to disable the Windows key with MS Powertoy, but it does disable on pydpainter too.
Anyway, I just Escape the windows menu and that's all. I do record a video and will add to our teaser.

**Comment by mriale** [comment]
I added some code to grab the mouse and keyboard in full-screen mode, so this should trap the Windows key for animpainting. Doesn't do anything on Linux, though.

**Comment by Sleuthgame** [comment]
Creating bouncing balls with spacing is way too much fun now. 😄 
![bouncingred](https://github.com/user-attachments/assets/fc16323c-81e2-4782-a3af-072bcc8799b7)

**Comment by Sleuthgame** [comment]
> It also automatically adjusts to the number of frames if you have the spacing option set to continuous.

It's very clever !

And having space settings working is a game changer for rectangle or any tools.

**Comment by Sleuthgame** [comment]
It's alive ! 🐛 🕷️ 

![bugs](https://github.com/user-attachments/assets/7b23be38-0c8f-494b-aeb5-1d941efaf2f1)
