### ISSUE TITLE
Left border issue

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#149]
When you reach the left edge of the screen, the pointer easily exits the application. You cannot draw from the first pixel of the left edge of the PyDPainter screen as the pointer is too attracted to the outside. the blank side on left is ignored.
This problem does not occur at the right edge.

All versions, full screen mode only, 1980x1020 screen, PC win10.

NOT A PRIORITY FOR 2.0

**Comment by mriale** [comment]
Changed how the mouse maps to the window to also allow for borders.

This also should fix the mouse behavior in full screen mode for a rotated portrait mode display. In this mode the mouse considered the tall screen height to map to the PyDPainter image which made positioning the mouse awkward.

**Comment by Sleuthgame** [comment]
Feel good to me. Thanks you ! It was annoying.
