### ISSUE TITLE
Animpainting tutorial

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#150]
75 % done ! 😃 💨

**Comment by Sleuthgame** [comment]
Ill be ready in less than 2 hours (it's dinner time, I have to stop).
Will upload it soon. So we have a tutorial for animation. 🎈

**Comment by Sleuthgame** [comment]
Almost done.
🤕 I found a bug !

**Comment by Sleuthgame** [comment]
![3balls](https://github.com/user-attachments/assets/8ecfb22a-115b-42e0-8da9-50b987fc85ef)

Finished !

**Comment by Sleuthgame** [comment]
Uploaded, @mriale please proofread. Good labor day !

**Comment by mriale** [comment]
Wow! That is a fun tutorial! It really shows off the new animation features. Well done!
