### ISSUE TITLE
Anim files from PPaint missing last two frames

### ISSUE THREAD

**Issue by DownshiftDX** [mriale/PyDPainter#156]
Just updated to 2.0.0 Flatpak on Linux. 

Attempted to load several of my character animation walk / run cycles created on an Amiga in PPaint and the last two frames are missing in each. (Each is supposed to be 8 frames long and appears as only 6.) Loaded a 60 frame animation I use for testing movement against 16px wide tiles and it also loads as only 58 frames.

I then loaded one of the animation files in DPaint IV (under emulation) and simply saved it again and reloaded into PyDPainter. It loaded correctly with all 8 frames. It seems there is something different about how PPaint is saving anim files. (I also noticed that PyDpainter seems to be converting everything to 20FPS when I almost universally save in PPaint at 10FPS.)

[Rotate10.anim.zip](https://github.com/user-attachments/files/16858778/Rotate10.anim.zip)

**Comment by mriale** [comment]
Thanks for the bug report. I think I only tested with ANIM files from DPaint. That means I missed some subtleties of the format. Thanks for supplying the file so I can reproduce it, too.

**Comment by mriale** [comment]
@DownshiftDX The version in the `develop` branch should work with the above file now. The number of frames is no longer truncated and the frame rate is set to 10 FPS. I had to test with other ANIMs and try to get all of them working, and I think they are now. Thanks for the example and the opportunity to improve PyDPainter's IFF code. If you find anything else weird, please let me know.

**Comment by mriale** [comment]
@DownshiftDX In case you missed it, I incorporated this fix into a new release 2.0.1

**Comment by DownshiftDX** [comment]
> @DownshiftDX In case you missed it, I incorporated this fix into a new release 2.0.1

Sorry I have been busy the last few days with work and am only now getting a chance to sit down at my PC. I will give it a test shortly.
