### ISSUE TITLE
Unable to draw when magnified when changing frames

### ISSUE THREAD

**Issue by em00k** [mriale/PyDPainter#157]
If I create an animation with say 20 frames, select the first frame and then use the magnifier to draw something simple, press 2 to move to the next frame the dot cursor disappears and I am unable to draw, turning off magnify then updates the image.

You should be able to draw in magnified mode and change frames and see the changes.

**Comment by mriale** [comment]
Ooops! Thanks for reporting this.

**Comment by mriale** [comment]
I fixed this on the `develop` branch. It had to do with the new layer functionality I added behind the scenes.

**Comment by em00k** [comment]
awesome - thanks guys!

**Comment by mriale** [comment]
@em00k In case you missed it, I incorporated this fix into a new release 2.0.1
