### ISSUE TITLE
Can't import this as frame

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#159]
I'm working on a dance clip into PydPainter.

It's a Filmora 13 png export. It load as Picture, but not as "import" frame because of the filename.
Danceuse_0.png
![Danceuse_0](https://github.com/user-attachments/assets/bfd830cb-4e55-41b8-8ea3-226a2a2b4a7f)

I have tried starting at 100 ( Danceuse_100.png) and it's working fine. What's wrong with this file ?

**Comment by Sleuthgame** [comment]
Is it a naming convention problem ? Should it start with 001 ?

**Comment by Sleuthgame** [comment]
So I should rename the first files to Danceuse_001.png, am I right ?

**Comment by mriale** [comment]
Yes. Like this:
File001.png
File002.png
...
File100.png

You can use 3 or more digits, but I think I have a limit of 9999 frames.

**Comment by Sleuthgame** [comment]
I'm pushing a little the program, exporting video as frames, loading it, reducing size, the palette. It's amazing. Great work !
