### ISSUE TITLE
Mouse won't leave PyDPainter fullscreen anymore

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#176]
I used to work with two monitors, especially when recording tutorials or writting reports, doc etc.
I have PydPainter full screen on monitor 1, and my other app on monitor 2.

With the very last update (2.0.1) I can't left PydPainter with my mouse moving it to the left or right ouside the Pydpainter screen.

Ad now hitting F11 make my two screens blinking to full black before displaying PydPainter again in a windows.

It's very annoying, I can't record any new tutorial.

**Comment by mriale** [comment]
If you hold shift when pressing F11, it will not grab the mouse and keyboard when it goes full-screen. This is currently in the `develop` branch.

**Comment by Sleuthgame** [comment]
It's working, thanks !
