### ISSUE TITLE
Gradient Fill orientation is disturbing

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#178]
![image](https://github.com/user-attachments/assets/fb8caae6-244d-4393-a8d2-5688fb04479b)
![image](https://github.com/user-attachments/assets/149d0bfd-80e4-4479-9ea1-23a8249182c3)
The gradient direction arrow on the palette does not match the gradient direction in the fill. This is inconsistent.

Going back and forth between the palette and gradient options just to change the direction of a gradient is a waste of time. It should be possible to click on the gradient icons to reverse.

I hope this can be improved, because it's typically the kind of trifle that penalizes new users.

**Comment by Sleuthgame** [comment]
Hey ! @mriale can you fix this for me ? It's such annoying. Will be my birthday present.

**Comment by Sleuthgame** [comment]
Thanks ! There are very close date (unfortunatly).

**Comment by mriale** [comment]
@Sleuthgame Happy Birthday! I had no idea the gradient fill direction was reversed until I started looking at the code. I corrected that. I also added an arrow to the Fill Type requestor:
![image](https://github.com/user-attachments/assets/014b3d41-d961-4216-a3ec-9b708cd1afa4)

This is now in develop.

**Comment by Sleuthgame** [comment]
Thanks you so much 🥇 !

**Comment by Sleuthgame** [comment]
Did you erase or squash it from the current develop version by mistake ? It was there and then I downloaded the latest beta version this morning to test the grid and it's gone!

Happy Xmas anyways.

**Comment by mriale** [comment]
@Sleuthgame 
> Did you erase or squash it from the current develop version by mistake ? It was there and then I downloaded the latest beta version this morning to test the grid and it's gone!

The arrow disappears when you have a color selected that isn't in a range. I should probably change it so that it just ghosts the gadget when there is no range because that would be more consistent. Maybe I should ghost the slider as well. I also want to left-justify the dither value number because it makes it look like the number goes with the arrow and most of the time it is under 10.

> Happy Xmas anyways.

And Merry Christmas to you too!

**Comment by Sleuthgame** [comment]
You tricked me with that disappearing ghost feature! 🤣 
It's Christmas, not Halloween! 🎄 👻

**Comment by mriale** [comment]
Now fixed. You will see 3 ghosts. It's a Dickens Christmas!
![image](https://github.com/user-attachments/assets/04a0e61a-a678-45bf-a5c5-d62598d0cbcd)

**Comment by Sleuthgame** [comment]
👍 
It's helping a lot new user to understand why there is no gradient available with a color without any range.
