### ISSUE TITLE
Hitting OK in Palette won't change cycling speed.

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#184]
1. Open **Palette**
2. Change **Cycling speed** value manually (enter a new value, do not use the speed slider)
3. hit **OK** button or enter key.

Nothing is changed. The new value is lost.

Happens in current master and develop.

**Comment by mriale** [comment]
I noticed that there was no code to take the value from the speed box and move the slider. The right GUI element for this type of interaction is a label, so I made the speed value be non-editable

**Comment by Sleuthgame** [comment]
The slider is easy to use anyway. I enter this value the first time because I had to copy the same value from another range/cycling, which is a rare use.
