### ISSUE TITLE
STENCILED BRUSHES

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#186]
_Extract of DPIII manual, page 10._

In DeluxePaint III, your stencil also affects brush pick-up; the Brush
Selection tool picks up only areas that are not locked by the stencil. This
feature helps you pick up just the right area with ease, and if you want
to pick up everything, you can turn the stencil off while you make your
selection.

In current version, stencils are ignored to pick up a brush.
![image](https://github.com/user-attachments/assets/c9ab74ff-c60a-40f3-9b71-47b92c8082b0)
![image](https://github.com/user-attachments/assets/e73d52e3-4243-42eb-9c7f-fa9f4d128645)

**Comment by mriale** [comment]
@Sleuthgame, it looks like @abutcher-gh fixed this. The changes are in develop now.

**Comment by Sleuthgame** [comment]
Superb !
