### ISSUE TITLE
SHIFT-G key

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#187]
I was surprised SHIFT - G don't pop up grid option. It was never the case in DP3. Instead, I found :

**Shift-G** -grid on and uses brush handle location as a grid point;
_The Grid constrains the action of the painting tools. If you use Shift-G to turn the grid on while using a brush, the grid will use the current brush handle position as one of its points._

That's usefull !

**Comment by mriale** [comment]
Ah, I hadn't remembered that! I just added it to develop. I also made the brush handle default to the upper left while grabbing when the grid is on so that the brush aligns to the grid properly.

**Comment by Sleuthgame** [comment]
Another suggestion : 
**From brush** button. Set Y and Y size to current brush size.
If I works on a 16x16 tileset, my current brush is 16x16 and I need a 16x16 grid.

**Comment by mriale** [comment]
Added "From Brush" to Grid requestor:
![image](https://github.com/user-attachments/assets/026f7e1c-477b-4587-992e-af18572c4f6d)

This takes the current brush size and copies it to the grid size. While I was there I added number spinners because it was simple to do.

**Comment by Sleuthgame** [comment]
>While I was there I added number spinners because it was simple to do.

That's convenient. Maybe something you can add to Spacing options ?

And **Animation / Set Frame Count**". This one had space and is only a number requester, it will be more efficient.

**Comment by Sleuthgame** [comment]
Something that's always bothered me, in the fill, spacing, symmetry and grid options.
You go to the options, change a parameter, click OK and the tool isn't activated. If I've changed a parameter, it's because I clearly intend to use the tool. Especially grid and symmetry.
I think this has always been the case in DPaint 3, but I wonder if it's understandable for new users. 
You'd have to ask the community on FB what they think.
