### ISSUE TITLE
[ and ] does not select previous and next color anymore

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#192]
On a AZERTY keyboard, thoses shortcuts are gone.
Were there any replacements I didn't notice?

**Comment by mriale** [comment]
@Sleuthgame The program is still looking for the Unicode characters `[` and `]` instead of a particular key. Do the `{` and `}` keys for changing the background color still work? They are handled the same way in the code.

**Comment by Sleuthgame** [comment]
Nope. :-(

**Comment by Sleuthgame** [comment]
Both Dev and master.

**Comment by mriale** [comment]
Looks like an update to PyGame might changed how the key press events came though. I added a special case for these characters: `[ ] { }`

**Comment by Sleuthgame** [comment]
Ouch ! Thanks for fixing that.

**Comment by Sleuthgame** [comment]
Test ok ! Both pairs are working again.
Those are ALT- key shortcuts, so there are difficult to reach. Once we have re-implemented all DPaint 3 keys, we have to figure out something more straightforward.

**Comment by Sleuthgame** [comment]
I love the way PyDPainter DPaint shortcuts does not interrupt any drawing tools. We can do this while drawing.
![image](https://github.com/user-attachments/assets/813ea6c7-05fa-413a-90c3-c737ef3a3b00)
