### ISSUE TITLE
Tricky behaviour with RIGHT brush grab with a previous brush

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#193]
Hi ! I found a tricky one. It's not a bug, it's very disturbing. It's not the right behavior.
_In fact, it's happening to me while recording a tutorial and I do not realize what's happens first._

1. Grab a (large to see what's happening next) brush.
2. Change **Fill Type** to **Warp** or **Pattern** (**Brush** type won't trigger the bug).
3. Use **Brush** Tool to grab a new brush, using the right button to erase pixels under the new brush grabbed.

An unexpected fill is applied with the current brush and FILL Type ! Even AA is working now ! Every time you grab a new brush with RIGHT button, a wrap/Pattern/AA fill is applied with the new brush as reference.

**Comment by mriale** [comment]
Oh that was weird! Now it ignores the current fill mode when removing the brush. Thanks for finding this and spelling out the steps so I could reproduce it.

**Comment by Sleuthgame** [comment]
You're welcome. Tested OK.
