### ISSUE TITLE
Does not work on macOS

### ISSUE THREAD

**Issue by gklka** [mriale/PyDPainter#2]
Installed the dependencies then ran it via command line by `python3 PyDPainter.py`. The window opens, and log shows:

```
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Display mode = 11000
('draw', 0, 12, False, False)
('circle1', 0, 10, False, False)
```

But the window remains empty and I get no menus or whatever.

**Comment by mriale** [comment]
I suspect the problem is on the resizing of the window when it first starts up. I created a pull request for this #3 . It's also on the new branch issue0002. Since I don't have access to a Mac, could you try this out, @gklka ?
