### ISSUE TITLE
Option to save default application window settings

### ISSUE THREAD

**Issue by DownshiftDX** [mriale/PyDPainter#28]
Window zoom, scanline/filtering, and pixel ratio settings are not saved between sessions of running PyDPaint.

Expected: Last used setting would be saved and loaded automatically or that there would be an option for the user to save the current settings as startup defaults.

**Comment by mriale** [comment]
Added menu item to develop branch:
* Prefs/Save Config  - saves current settings
* It loads these settings at startup
Will incorporate this into a new release within about a week.
