### ISSUE TITLE
Menu behavior is inconsistent with Amiga DPaint

### ISSUE THREAD

**Issue by DownshiftDX** [mriale/PyDPainter#29]
The current menu behavior is not the same as on the Amiga or DPaint. If the user puts the pointer over the screen bar it shows the menus immediately and menus can be accessed with either mouse button. Amiga menus are accessed with the right mouse button and only shown while holding the right mouse button. As a almost literally life-long DPaint (and now PPaint user) this "feels" odd.

The current behavior may be intended for discoverability needs.

**Comment by mriale** [comment]
Added menu item `Prefs/Hide Menus` to hide the menus until you click on them just like the Amiga does. However, I left it that either button can bring up the menus, but it still feels like an Amiga if you just use the right button.

`Prefs/Save Config` also persists this setting and the rest of the Prefs menu settings now.

This is now in the `develop` branch. I hope to have a new release within a week.
