### ISSUE TITLE
Filerequest bug crash and exit

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#35]
Hi !

Thanks you so much for such an amazing tool !

If you mispell the drive letter (ie: C:\) with two letters and hit enter, there is a bug and PyDpaint crash.
ie :
![image](https://user-images.githubusercontent.com/130657737/231733961-b96638b4-826c-4d6e-8d77-c68d91194cf1.png)
Bug windows :
![image](https://user-images.githubusercontent.com/130657737/231734320-b6de5d3a-85c8-4c72-9431-bb1e76a35b1e.png)

**Comment by mriale** [comment]
Fix is on develop branch and will incorporated into a release in a few days..
