### ISSUE TITLE
Wrong opening of low res screens size PNG as default VGA

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#37]
If you open a 320x256 PNG file in 256 colors, it opens as a small vignette in the center of a 640x480 VGA 256 colors screen.
Palette is ok.

![image](https://user-images.githubusercontent.com/130657737/231835904-28f71687-ea78-48ce-9453-5aad4efc6e42.png)

The temporary solution is to change Screen format and convert back to PAL 320x256 Lo-Res without requiring resizing (Resize Page : No).

![image](https://user-images.githubusercontent.com/130657737/231837053-3fa96338-f464-4b2f-bca6-c0fa3b442e4d.png)

Done !
![image](https://user-images.githubusercontent.com/130657737/231836534-adbeb60e-6b6e-4905-bcc5-091a0a971982.png)

**Comment by Sleuthgame** [comment]
Using 1.0.5. and a proper PNG file in 320x256 exported from PhotoShop here.
![bedroom_low32c](https://user-images.githubusercontent.com/130657737/231838236-65d532de-fc7a-4868-8b0e-e060d1d3cecb.png)

**Comment by mriale** [comment]
I marked this as an enhancement because it's really just making PyDPainter smarter at guessing the proper resolution for imported files. I'm thinking it could see if it has an exact match for one of the resolutions and use that one.
