### ISSUE TITLE
Add Support for IFF PBM format

### ISSUE THREAD

**Issue by RetroNick2020** [mriale/PyDPainter#40]
This variant is used by Deluxe Paint on PC for 256 color modes.
Even though the header indicates that it is 8 bitplane format. Its actually a single bitplane with colors being  8 bit.
header is "PBM " instead of "ILBM".

**Comment by mriale** [comment]
Thanks for filing the issue. I remember you had mentioned it in your YouTube comment.

I was able to load an IFF PBM format picture into PyDPainter because apparently it is one of the image formats PyGame 2.x supports. Do you need the extra information in the IFF chunks like the exact color map (CMAP) and color cycling ranges (CRNG)? Also do you need to save pictures in the IFF PBM format?

**Comment by RetroNick2020** [comment]
yes. saving would be good.  I think i tried to load as brush and it loaded  like the planar modes.

if you need sample pictures in different sizes let me know.

**Comment by mriale** [comment]
@RetroNick2020 I added native read support for IFF PBM for now to the `develop` branch. It worked with the `BLUPRINT.LBM` I re-saved in IFF PBM format. If you could attach a few good sample files to this issue, that would be helpful. Also, if you could test out the read functionality in the `develop` branch, that would be good too.

**Comment by RetroNick2020** [comment]
Tested on develop branch.
Reading DP DOS PBM files in 320x200 format works. This includes opening as brush. Here is the sample images i created in DP Dos. I will do some more testing tomorrow. I had to zip it, github doesn't like plain LBM files
[TESTPBM1.zip](https://github.com/mriale/PyDPainter/files/11246087/TESTPBM1.zip)

**Comment by RetroNick2020** [comment]
Discovered a problem. It looks like non standard sizes break the loading for PBM
Here is an example. this is a 299x200x256.

[TESTPBM2.zip](https://github.com/mriale/PyDPainter/files/11251087/TESTPBM2.zip)

**Comment by mriale** [comment]
@RetroNick2020 I fixed PBM image loading for non standard sizes. I also added image saving in PBM (LBM) format. I was able to load these LBM images into Deluxe Paint II Enhanced for PC and also in GrafX2. These changes are in the `develop` branch, so please test them out to make sure they work with all your files. Thanks!

**Comment by RetroNick2020** [comment]
that's great! everything is working correctly
