### ISSUE TITLE
Opening Screen Format causes crash

### ISSUE THREAD

**Issue by DownshiftDX** [mriale/PyDPainter#41]
After opening an EHB image, selecting Screen Format causes a crash.

Steps:
1. Start PyDPainter 1.0.7
2. Open an EHB image.
3. Attempt to open the Screen Settings menu.

Repro: 5/5 with different lowres EHB images.

Result:
Crash with the following output:

raceback (most recent call last):
  File "/home/joshua/Applications/PyDPainter/PyDPainter.py", line 56, in <module>
    config.run()
  File "/home/joshua/Applications/PyDPainter/libs/config.py", line 1253, in run
    me_list = self.menubar.process_event(self.screen, e, self.get_mouse_pointer_pos)
  File "/home/joshua/Applications/PyDPainter/libs/menubar.py", line 374, in process_event
    attrs["menu2"].action.selected(attrs)
  File "/home/joshua/Applications/PyDPainter/libs/menus.py", line 245, in selected
    screen_format_req(config.pixel_req_canvas)
  File "/home/joshua/Applications/PyDPainter/libs/menureq.py", line 409, in screen_format_req
    while modes[res].mode_id != config.display_mode:
IndexError: list index out of range

Notes:
I was not able to reproduce this on an image with less than 64 EHB color mode. 
Also, on my real Amigas and under emulation I tend to use overscan screen modes in DPaint and PPaint, and my defaults are 352x240 NTSC and I work in 1:1 pixels. I can submit an image for testing if desired.

System: Linux Mint 21.1 Cinnamon

**Comment by mriale** [comment]
@DownshiftDX Thanks for reporting this. I think this has been a bug nobody has caught for a while. I just fixed it in the develop branch. Could you verify that it works for you?

**Comment by DownshiftDX** [comment]
Just pulled the dev branch and tested and it looks like it is fixed there. I couldn't reproduce the crash after trying several EHB images with various sized overscan.
