### ISSUE TITLE
PyDPainter should respect pixel ratio setting when loading an image. (Enhancement request)

### ISSUE THREAD

**Issue by DownshiftDX** [mriale/PyDPainter#42]
I always work in 1:1 pixels since getting back into the Amiga several years ago. PyDPainter overrides the manually set and saved preference for 1:1 on loading an image and each time I need to toggle it back to see the image correctly. An option to to lock the aspect ratio would be welcome.

**Comment by mriale** [comment]
Added a new menu option: Prefs/Force 1:1 Pixels

@DownshiftDX Can you grab the `develop` branch and test this out? I played with this some, but I'm not sure I caught all the special cases. Thanks!
