### ISSUE TITLE
Ctrl should leave traces with line or shapes tools.

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#45]
![image](https://user-images.githubusercontent.com/130657737/233609133-dacf2afc-b117-4631-8d0a-7d69b548c723.png)

**CTRL key** for tracing tools not supported.

Dpaint has a special drawing mode, when hitting the CTRL key while using theses drawing tools :
- line
- circle
- rectangle
- maybe ovale.

It lock the origin point, then it draws automatically shapes while the user was playing with his mouse. It allow for easy and nice effects.
I have tried reproduce them one by one on my example. It's described page 4.33 in the DeluxePaintII manual : SPECIAL KEYS. **Ctrl** leave traces with line or shapes tools.
Obviously, the relative slowness of DPaint to draw must be respected, otherwise with current machines, there will not be time to move the mouse fast enough before all the pixels are drawn.

**Comment by Sleuthgame** [comment]
I obviously failed at keeping a constant origin point in my LINE example. ^^

BTW, using this technique with CYCLE MODE was very efficient to paint some psychedelic stuff in seconds.

**Comment by mriale** [comment]
I added this to the `develop` branch. Some differences from DPaint:
- The `CTRL` key has to be held the entire time while leaving traces rather than just before the mouse button is pressed
- The `CTRL` key can pressed and released while dragging to leave traces or not
- The curve tool doesn't have this functionality because I thought is wasn't that useful.
- There is a 60 millisecond delay between traces being left to allow you to be able to control the traces better

**Comment by MetinSeven** [comment]
Sorry for reopening this thread, but holding Control doesn't leave traces when I try it in version 1.0.8, is that correct? Maybe it's postponed to a future update?

I'm using the executable on Windows 11.

**Comment by Sleuthgame** [comment]
Yes, it's in version 1.0.9. or dev.

Quoting Mark :

> To run the development version, you have to install Python:
> 
> https://www.python.org/downloads/
> 
> After that, you can choose the develop branch:
> https://github.com/mriale/PyDPainter/tree/develop
> and pull down the "Code" button on the top right to download a zip file.
> 
> After you unzip that, you can double click on the script "install_pygame.bat". You only need to run this once to install the necessary Python libraries.
> 
> After all that is done, you can then double click on PyDPainter.py and it will run.
>

**Comment by MetinSeven** [comment]
Ah, OK, thanks! I guess for this one feature I'll just wait until it's present in a next release. 🙂

**Comment by BleuLlama** [comment]
I thought this feature only happened with Deluxe Paint 1, Maybe with DP2... but was removed with DP3...

**Comment by Sleuthgame** [comment]
> I thought this feature only happened with Deluxe Paint 1, Maybe with DP2... but was removed with DP3...

Actually in the Manual of DPaint 3 and 2. I remembered this function while listing the keyboard shortcuts for reference.

**Comment by MetinSeven** [comment]
I sure remember it, a nice function for some playing around. Can't remember really having used it for an actual work.
