### ISSUE TITLE
Add stencil tool

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#46]

**Comment by MetinSeven** [comment]
> It's amazing ! Maybe : Keep adding colors to stencil while draging the mouse on the screen with LEFT button. Actually it remove if already selected. Remove colors of stencil while draging RIGHT mouse button on the screen ?

Yes, I'd like that too. Great work, Mark!

**Comment by mriale** [comment]
@Sleuthgame @MetinSeven Oh, so like the way DPaint does it? :smile: Ooops! I didn't figure that out until a few minutes ago. It's in the `develop` branch now.

**Comment by Sleuthgame** [comment]
Thanks.

I can't believe how the body remembers this! Because I didn't think of it! My hand just felt like doing it that way. 30 years later, my hand remembers more than my brain! OO

**Comment by MetinSeven** [comment]
> I can't believe how the body remembers this! Because I didn't think of it! My hand just felt like doing it that way. 30 years later, my hand remembers more than my brain! OO

Haha, yeah, I'm also suprised by how my dusty memory manages to recall all DPaint keyboard shortcuts. 😃

**Comment by Sleuthgame** [comment]
Stencil On/off.
Actual Shortkey ``` is unreachable on a AZERTY keyboard. It's something like ALT-7 and press another key. Can you double it with ² ? This key is left the number 1 & keys, above TAB, very easy and exactly the same place as Amiga ` where.

**Comment by mriale** [comment]
@Sleuthgame I think stencil toggle should work now on AZERTY. I added support for the ² key.

**Comment by Sleuthgame** [comment]
Thanks. Yes it works.

Strange behaviour : 

1. Make a stencil with several colors.
2. Paint something.
3. turn stencil off with short key.
4. paint again.
5. turn stencil on again. All last drawing with stencil off are redraw with stencil on.

**Comment by mriale** [comment]
@Sleuthgame It wasn't storing the mask, so when you toggled the stencil, it just drew what was overlaid before. Now it stores a mask and recalculates the overlay image when the mask is toggled on. I think that makes it behave properly. Please check it out.

I also added a stencil indicator in the title bar. I hope to add more indicators like fill mode soon (Issue #69).

**Comment by Sleuthgame** [comment]
Yes, it works.

Oh yeah, I love waht you did ! This inverted S stencil indicator is so DPaint style. Very cool.

**Comment by Sleuthgame** [comment]
There is a side effect of Stencils. It copy the stencil content in Spare page. Create one and hit j. Oups !

_

> Bugs that keep their secrets
> Will unfold behind the screen
> And there upon a github
> Is the answer to a neverending story
> Ah
> Neverending story
:^D
_

**Comment by mriale** [comment]
@Sleuthgame Ah! Thanks for finding that! Now it just disables the stencil when swapping. DPaint has a stencil state for each page which seems confusing to me since they share the same stencil.

**Comment by mriale** [comment]
I also noticed that undo/redo did weird things with stencils, so I fixed that.

**Comment by Sleuthgame** [comment]
I will try to stress test it again. When you intend to release ?
Remember to use my iff pictures as sample if you need.

**Comment by mriale** [comment]
I was just doing some more stress testing, and I found that all the Picture menu items looked a little bad with the stencil on: Open, Flip, etc. I turn off the stencil now when those items are selected. I hope to release this in the next few days. I have some time now to devote to it and want to get it right.

**Comment by Sleuthgame** [comment]
Oh, absolutely.

Use a pic with a stencil. Drag and drop a new file. It's importing, but the picture with protected colors are still here !
Somehow, it can be a functionality ;-)))

**Comment by Sleuthgame** [comment]
- Stencil/Free is erasing the whole screen.
- Stencil/Reverse not implemented, isn't it ? I have tried in 2 colors, 32...

**Comment by mriale** [comment]
@Sleuthgame OK, I made a bunch of changes and re-implemented stencils using an actual mask which I thought would be slow but turned out to be pretty fast. I tested it some, and I think it's working better. Sorry for all false starts here. I guess this is what it looks like to watch the sausage being made -- a little messy! :smile:

**Comment by Sleuthgame** [comment]
Let's toast this new sausage ! :-D

**Comment by Sleuthgame** [comment]
I have made very some stress full tests, but not for a long time. Nothing unexpecting. Works fine :-)
Maybe release a new beta and ask for feedback.
