### ISSUE TITLE
Works on macOS 13.2.1 (Ventura) ARM (M2) macmini

### ISSUE THREAD

**Issue by cstrotm** [mriale/PyDPainter#5]
Just an information - works on macOS

**Comment by mriale** [comment]
Thanks for testing!

**Comment by MetinSeven** [comment]
> Just an information - works on macOS

Hi Carsten,

Could you maybe share your ready-to-run macOS version? I'm not familiar with compiling, but love to have the latest PyDPainter for macOS.

Many thanks in advance.

**Comment by mriale** [comment]
> @cstrotm Hi Carsten,
> 
> Could you maybe share a download link to your ready-to-run Apple Silicon macOS version?

I did end up buying a used Mac Mini a few weeks ago and was able to build a Mac .app version. I'll upload that to GitHub when I get a chance probably as a .zip file. I'm also planning on buying a developer license so I can publish to the Mac store, but I think I'd like that to be the new release with the move requester-like features which aren't quite done yet. You can track the progress here: #123

**Comment by MetinSeven** [comment]
That's great news, Mark, many thanks! 👍

**Comment by mriale** [comment]
@MetinSeven 
Added a Mac beta build to the last release. Not sure if I got it right. Please test it out:
https://github.com/mriale/PyDPainter/releases/download/v2.1.0/PyDPainterMac-beta.zip

**Comment by MetinSeven** [comment]
> [@MetinSeven](https://github.com/MetinSeven) Added a Mac beta build to the last release. Not sure if I got it right. Please test it out: https://github.com/mriale/PyDPainter/releases/download/v2.1.0/PyDPainterMac-beta.zip

Hi Mark,

Thanks a lot! It seems to work fine. I've changed some settings, drew something, changed draw mode, opened a file, no strange behavior. The preferences also seem to be stored correctly. I reopened the app, and the settings were still intact.

I hope future releases will include a macOS version. Thanks again! 👍👍

**Comment by MetinSeven** [comment]
@mriale Just one wish for now: could you please add Command + Z as an alternative Undo keyboard shortcut, and Shift + Command + Z as an alternative Redo shortcut? Those Undo and Redo shortcuts are very hardcoded in my brain, and undoubtedly in the brain of many others. 😅

Many thanks in advance!
