### ISSUE TITLE
Rotate / turn ellipse

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#50]
The ability to rotate ellipses. This was probably never a feature of DPaint, but I have used it at least on Brilliance 2 on Amiga. It is so useful to draw Saturn rings on planets, orbits. In fact ellipses are more useful at an angle.

The ergonomics was that while drawing, after the first left click to draw the oval, you could press the right button and move the mouse to tilt. But it can work with a key too. The tilt is done over a 90° range, not more. More is not necessary since the shape is symmetrical.

**Comment by mriale** [comment]
@Sleuthgame Now it works pretty much like Deluxe Paint III. You drag out an ellipse, let up and then drag it to rotate to an angle. This is in the develop branch. Can you try it out?

**Comment by Sleuthgame** [comment]
I'm trying it right now. It works very well. I have tested all the fill modes with it. I have a habit of using the right button to tilt, I don't know why.
>> Think to update the tooltip.

**Comment by MetinSeven** [comment]
> @Sleuthgame Now it works pretty much like Deluxe Paint III. You drag out an ellipse, let up and then drag it to rotate to an angle. This is in the develop branch. Can you try it out?

Looking forward to seeing this added to the Windows release executable. 👍

**Comment by Sleuthgame** [comment]
![image](https://user-images.githubusercontent.com/130657737/235878285-b435e3a0-a9b3-4ad6-8e70-70f7ec0c6095.png)
When you're inclined to be elliptical. ^^

**Comment by mriale** [comment]
@Sleuthgame Nice art! Also thanks for testing it out.
I added instructions to the the tooltip and also made rotation work better with non-square pixel modes like medium res and interlaced low res.
