### ISSUE TITLE
Color Palette / Copy does not refresh/select destination container values

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#52]
1. Open Palette
2. **Copy** one color to another color. It's working.
The current selected color is now outlined with a white line, okay.
3. Play with any R G B H S W bar. The values were stuck on previous color. The copied color has vanished.

bug workaround : select the new color before adjusting rgb hsv colors bars.

**Comment by mriale** [comment]
Thanks for finding this obscure bug and making it easy to reproduce. This now is fixed in the `develop` branch.
