### ISSUE TITLE
Filled Rectangle, filled circle, ellipse do not support Cycle Mode

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#53]
Fill tool and polygon tool support Cycle Mode.
Filled Rectangle, filled circle, filled ellipse do not support Cycle Mode. Stuck to actual color.

Filled free form has a strange behaviour : a click drawing the shape, it jump to next color of the cycle.

**Comment by mriale** [comment]
Thanks for the details on this! I thought I already had this working before, but I guess not. This is now fixed in the `develop` branch.
