### ISSUE TITLE
Can we use keyboard like vim?

### ISSUE THREAD

**Issue by miratcan** [mriale/PyDPainter#62]
| Header | Header |
|--------|--------|
| J | Go one pixel DOWN |
| K | Go one pixel UP |
| H | Go one pixel LEFT |
| L | Go one pixel RIGHT |
| 1,  2,  3, ...  | Select color from palette |
| I | Insert pixel |
| 12,12gg | Go to position 12, 12 |
| : %s/12/3/g | Change all pixels with color 12 to 3 |

etc...

**Comment by mriale** [comment]
While this doesn't fit in the vision I have for PyDPainter, I think it is an intriguing concept for a new project maybe: a keyboard-based paint program with vi key mappings. Try it yourself! It looks like you have a bunch of cool projects already.
