### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by BleuLlama** [mriale/PyDPainter#63]
The real dpaint (at least one version i can remember of it) would let you specify a file to load from the command line.  
eg:
    CLI>  dpaint splash.iff

It would be nice to be able to specify a file or files to load on startup.
On top of that, it would be nice to be able to specify the directory that the file requestor starts in, or define "assigned logical drives"/aliases for use within the file requester, either on the command line or in a user config file.

    # PyDPainter.py  --req_dir ~/PyDPainter/iff_pics --font_dir ~/Amiga/fonts  --assign PICS=~/Amiga/lo-res --assign DEV=~/proj/mygame/images

etc...

**Comment by mriale** [comment]
Thanks for your ideas! Right now PyDPainter can take one argument which is the filename to load. Also, the hidden file `~/.pydpainter` is loaded on startup that has a number of configuration settings saved if you select _Prefs/Save Config_. That's interesting to have the startup directory specified on the command line. Maybe it also makes sense to put that in _Prefs/Save Config_. When the Amiga font loading is implemented, it will need paths for that as well. The assigns seem interesting, although you could probably just put symbolic links in a directory to simulate that without adding that to PyDPainter. Other than saving state which can be done using `~/.pydpainter`, can you think of other command line options that would make sense to implement?

**Comment by BleuLlama** [comment]
Huh. I tried to include the filename on the command line and it didn't work... but i realize now i was attempting to load a PNG which doesn't normally load correctly anyway.  My bad on that.

And about the only thing that might be useful is to set a different config to load.  Like, if i were to run it generally, i might want it to default to my account's directories, screen resolution, aspect, etc...  but if i'm using it with a specific project, i might want it to be set up with a different configuraiton.

I know it's a stretch, but I feel like i gotta save face now that I've learned that the "lack of feature" i was reporting was mainly a "lack of braining" on my part. ;D

**Comment by mriale** [comment]
@BleuLlama 
- Added a command line parser so that command line arguments can easily be added.
- Added argument `--config` to load an alternate config file.
- The filename argument still works
- Added `filepath` to the config file to save the path where the file requestor opens

These changes are now on the `develop` branch and will hopefully be released in the next few days.
