### ISSUE TITLE
Frequent crashes after multiple undos

### ISSUE THREAD

**Issue by MetinSeven** [mriale/PyDPainter#64]
Hi Mark,

I'm frequently encountering PyDPainter crashes surrounding undo actions.

I'm not sure yet what exactly triggers it. It's one of these actions:

1. Multiple undos (repeatedly pressing Control + Z).
2. Multiple undos followed by a Redo (Control + Shift + Z).
3. Saving the image right after one or multiple undos.

It might very well be number 3 out of this list. See also this screenshot of the error:

<img width="359" alt="image" src="https://github.com/mriale/PyDPainter/assets/18738261/794b2260-c2fc-47f0-87dd-a38ca114e7ac">

**Comment by mriale** [comment]
@MetinSeven Sorry, that must be frustrating! I've tried this several different ways, and I haven't been able to trigger the bug. Can you give exact steps for when it crashes for you (screen mode, how many undos/redos)? Does it also happen with an IFF file? The bug could be in the PNG file save built into Pygame.

**Comment by MetinSeven** [comment]
🤔 I also can't reproduce the crash once I start PyDPainter and start testing. I suspect it starts occurring when working in PyDPainter for a certain while. Maybe a Python-related memory leak? I'll keep an eye on it.

**Comment by mriale** [comment]
@MetinSeven Do you have any additional insight on this? Is it still happening? Is it only when saving PNG files and not IFF files? I'll probably close this soon if I can't recreate it or find what to fix.

**Comment by MetinSeven** [comment]
Hi Mark,

I'm still encountering these crashes. I don't know if they have got something to do with undo / redo, but the crashes seem to increase in frequency with every crash + app restart, as if some reserved RAM space gets corrupted along the way.

Here's the latest error message:

> Traceback (most recent call last):
>   File "PyDPainter.py", line 56, in <module>
>   File "config.py", line 1407, in run
>   File "menubar.py", line 406, in process_event
>   File "hotkey.py", line 38, in press
>   File "menus.py", line 83, in selected
>   File "picio.py", line 504, in save_pic
> pygame.error: Couldn't open D:\Pixels\The creatures under my bed\Bed Creatures V01.png

When it occurs, it always occurs when saving using Control + S. Then the latest version is not saved. Luckily I tend to save frequently.

**Comment by mriale** [comment]
@MetinSeven I added in some error trapping in the `develop` branch so if it has a problem saving a file, it brings up a requestor that says it was unable to save the file. PyDPainter should now keep running and won't suddenly quit.

However, that doesn't answer the question why it is having a problem saving the file in the first place. It could be you have some program in the background backing up the image files, and it is backing up the file while you are trying to save over it. Is Dropbox or Sync or something else running on that directory?

**Comment by MetinSeven** [comment]
Thanks Mark! Knowing that the latest version is saved despite an error occurrence is very comforting.

I've indeed got a cloud backup service running in the background. It's a interesting thought that it could be the culprit if I save too frequently. I'll keep an eye on my saving frequency relative to the crash occurrences.

**Comment by MetinSeven** [comment]
Update:

It seems indeed that the crashes are related to high-frequency saving, possibly in combination with a running cloud backup of the file, as you suggested.

I'll try to reduce the saving frequency and see if that reduces or eliminates the errors.

**Comment by MetinSeven** [comment]
I hope this is the same bug.

**Comment by mriale** [comment]
Saving a picture or brush in the root file system crashed the program before because it needed elevated rights. Now it properly traps the error:
![Screenshot_20230903_150034](https://github.com/mriale/PyDPainter/assets/26576606/d69134e8-e9da-4472-a6b6-673c4154cfc5)
![Screenshot_20230903_152233](https://github.com/mriale/PyDPainter/assets/26576606/7eb91ff7-74bb-4a1c-8ec9-82870d35c710)
