### ISSUE TITLE
Display Coords while using PLACE Simmetry

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#68]
Usefull to place symmetry in a specific place on the screen, like an half or a third of screen.
Actually Coords don't show while using Place.

Maybe some "Center X","Center Y" or reset buttons will be usefull to replace symmetry in center by default after custom placing.

**Comment by mriale** [comment]
In the Symmetry Requestor, I added:
- Coords in the title bar during Place
- Editable center coords fields
- Center X and Center Y buttons

**Comment by Sleuthgame** [comment]
It's working. I have tried to mess it with flip coords and weird changes but it does not trim bugs. :-)
