### ISSUE TITLE
Stencils and Palette

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#71]
1. Use 640x512 screen like Amiga PAL hires.
2. Use airbrush, draw some white stars with.
3. Create a stencil to protect black background color.
4. Use square fill to recolor some star in red, blue, etc.
5. Stencil is still on. Hit P for palette. Use it.
Aera filled are now buggy and you can see the filled squares.
:'(

**Comment by Sleuthgame** [comment]
Wait, actually if you call Palette, the stencil is turned off.

It's a turnoff. :-)

**Comment by mriale** [comment]
@Sleuthgame Thanks for an easily repeatable process. I patched this on the `develop` branch, and it seems to fix the weird glitches you were seeing. I also changed the code to leave the stencil on when you bring up the palette requestor.

**Comment by Sleuthgame** [comment]
You're welcome ! I'm very busy right now. I will try to catch new bugs later. 
And begin to use it more creatively. ;-)
