### ISSUE TITLE
Implement Fix Background

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#73]

**Comment by Sleuthgame** [comment]
Invent a "Load as background"
Load image as background. Display as a visual reference without any change of current screen, page size and palette of current projet.

**Comment by Sleuthgame** [comment]
Is this something different from the reference layer ? I'm confused.

**Comment by mriale** [comment]
This is to implement Deluxe Paint's Background functionality, but maybe I can morph this into the genlock layer from Issue #67 because it's really doing much the same thing.

**Comment by mriale** [comment]
Still a little buggy, but I added this commit: 649936f9397efdbba6b5587f6cc9e2afe0754348 and forgot to mention the issue number.
- Added `Effect/Background/Open...` to load a reference picture
  - This adds an `R` indicator (reference) rather than the normal `B` indicator (background)
- Added `Effect/Background/On/Off` to toggle the background layer (shortcut key: `\`)

I think I want to rename some of these menus:
- Fix -> Grab
- Free -> Stamp

I also don't like the `R` and `B` indicators.

Any ideas how to make this better?

**Comment by Sleuthgame** [comment]
OK. Busy weekend. I'll watch after this sunday.

**Comment by Sleuthgame** [comment]
Testing it... This is very good ! I love it ! 👍 

My 2 cent : Fix / free are very easy to understand for "international user". I do not understand stamp in this context.
\ is hard to access in AZERTY - it's ALT GR 8. Maybe asterisk * ?

B and R are fine. Do you prefer icons ? But Reference and Background are not standardized icons either.

Maybe ask the facebook group.

**Comment by Sleuthgame** [comment]
![image](https://github.com/mriale/PyDPainter/assets/130657737/bcbc86a4-7f35-48b6-a8dc-c9f5a1c56494)
This is soooo useful... The only "issue" I see (apart the hard to access toggle key) is that now I want a eyedropper tool to catch color from reference background in Palette.

Graphic artist ? They are NEVER happy. :-D

**Comment by mriale** [comment]
Graphic artists never happy??? :smile:

I added a `Pick` button to the color palette that will pick a color from the screen into the selected slot. If you have a background or reference image visible, it will grab the color from that.

Also I changed the keyboard shortcut for the Background toggle on/off  to `CTRL-B`. The `*` key is used in DPaint for animation to go to the last anim brush cel. I think I will use control-keys for new functionality since I don't think these were used in DPaint.

**Comment by Sleuthgame** [comment]
It's working like a charm.

I'll search for a personal reference pic we can use as tutorial and announcement (pic above is from japanese artist Hiroshi Nagai)

Happy !

**Comment by Sleuthgame** [comment]
hi ! Please use following screenshot as needed for communication, reference etc.
![image](https://github.com/mriale/PyDPainter/assets/130657737/d407e6b9-6abb-4402-9905-1fa0ed3de5db)

The 3D picture is from me, it's a Cinema4D render of mine explaining how to create perfect reflections grounds.

**Comment by mriale** [comment]
@Sleuthgame I think I got all the edge cases for the background functionality. The most annoying one was that background colors other than 0 were doing strange things. So I just force the background color to be 0 whenever there is a background.

Oh... I didn't fix the Save yet. It needs to flatten the background when saving. Right now it will only save what you've drawn over the background.

**Comment by mriale** [comment]
I updated it to save the background with the picture unless you toggle the background off. Show Page works the same way too now. I'm hoping the background functionality should be solid now.

**Comment by Sleuthgame** [comment]
Load reference background.
Draw this using default color
![image](https://github.com/mriale/PyDPainter/assets/130657737/20ac9aee-b4fb-408e-bda5-2aacf7d7744f)
Save default (iff).
New or quit.
Load it.
![image](https://github.com/mriale/PyDPainter/assets/130657737/9a1ec273-e77b-42fd-a656-5ba3dcfa3f23)
Some colors are changed, red is ignored.

**Comment by Sleuthgame** [comment]
New test. Hi-res PAL 16 colors.
Upload jpg reference.
Pick new colors from reference.
Draw some
![image](https://github.com/mriale/PyDPainter/assets/130657737/752e0ed3-ca43-4341-9324-3e092523c654)
Save (background reference is on)
New.
Load iff again. All colors messed up. See below :
![image](https://github.com/mriale/PyDPainter/assets/130657737/4f12164a-b1f5-4368-acc0-bc455f822a33)

**Comment by Sleuthgame** [comment]
Okay, I have a lead. It might only happen with 16 colors. I tried med-res and hi-res 16 colors it mess.
I have tested 256 colors low res, same pic, it works.

**Comment by mriale** [comment]
Some weird bugs here! Thanks for finding them. These should now be fixed in `develop`:
- When a reference image is showing, saving the picture wrote an image with mixed up colors and missing colors
- Loading XGA pictures didn't size the canvas appropriately and then crashed the program
