### ISSUE TITLE
Smooth mode available in fill tools

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#75]
Well, I do not know if it's easy or not, but I think smooth will behave more regularly if used in a filled shape than painting with brush.

Painting smooth is more a fx/paint tool to achieve effect. It's Dpaint legacy. I know how to use it. 

But nowadays, anti aliasing is supposed to be more efficient. Maybe filling with smooth ?

Or a new Smoothing mode (SuperSmooth) who alias pixels but do not lower brighter colors and sink/blur details ?

**Comment by mriale** [comment]
I added 2 fill modes to the fill requestor: Antialias and Smooth. These are mostly untested at the moment, so there are probably bugs in them. The algorithm I use for the anti-aliasing is Scale2X, which is implemented natively in PyGame. I have a bitmap in the fill requestor to preview the 2 new fill modes:
<img src="https://www.scale2x.it/snap/test-1x.png" width="14%">

This is the image anti-aliased:
![image](https://github.com/mriale/PyDPainter/assets/26576606/6edbf9e7-e286-4148-b51f-6a183c429c94)

This is the image smoothed:
![image](https://github.com/mriale/PyDPainter/assets/26576606/00415a4a-047a-4292-9180-a3f737de9fed)

Please take a look and let me know if it's worth it to add these modes.

**Comment by MetinSeven** [comment]
Interesting, I thought Scale2X simply interpolated 2 x enlarged pixels with the same value, but apparently you can also determine the color / value of the interpolated pixels?

**Comment by mriale** [comment]
Instead of the weird image, I put the text of the fill mode in the preview:
![image](https://github.com/mriale/PyDPainter/assets/26576606/983ba117-0882-4e25-9e2f-02d28514e190)
![image](https://github.com/mriale/PyDPainter/assets/26576606/7080d7cb-9d9f-45ed-9b58-b687a48688e5)

I also fixed some cases where the fill mode indicator was not getting redrawn properly.

**Comment by Sleuthgame** [comment]
Hi ! I'm back :-)

Awesome. Can't wait to test it.

**Comment by Sleuthgame** [comment]
Some tests I made. Both are very quick and usefull.

![test-AA-1](https://github.com/mriale/PyDPainter/assets/130657737/061c6efe-350a-4e99-af98-b65e4fa4b41b)
![test-AA-2](https://github.com/mriale/PyDPainter/assets/130657737/3ec04d51-0eea-478d-a4b0-2269d3e77628)

**Comment by Sleuthgame** [comment]
Maybe more visible on screenshoot than lowres files.
![image](https://github.com/mriale/PyDPainter/assets/130657737/b7d39093-0dd2-42aa-91ee-98145a10c16d)
![image](https://github.com/mriale/PyDPainter/assets/130657737/b6334a02-2f69-492c-8366-8a0d20adfdf1)

**Comment by Sleuthgame** [comment]
![image](https://github.com/mriale/PyDPainter/assets/130657737/75134837-26a7-4ebc-81ef-4b31ebd5a466)

**Comment by Sleuthgame** [comment]
May I advice you to :
1. Use CAPS LETTER for prewiew texte and fill mode bar ?
ANTIALIAS
SMOOTH
because A,N and M letters creates interesting diagonal lines.
2. Use AA instead of An in bar. More explicit.
3. Maybe use diagonal shapes like in symbols / X \ as second line preview ?

**Comment by Sleuthgame** [comment]
Classing 3 chessboard AA test.
![image](https://github.com/mriale/PyDPainter/assets/130657737/d5d3cf58-ac61-414b-a781-074bf779f6b2)

**Comment by MetinSeven** [comment]
Ah, nice memories of DPaint's Perspective function. ❤️

**Comment by mriale** [comment]
I re-added the weird preview image that I had in a previous version, but I had removed it because I thought it didn't work. I think it works with the label now:
![Screenshot_20230809_222532](https://github.com/mriale/PyDPainter/assets/26576606/4e933d1a-ba95-42e9-aba1-82d0a29d729f)

This image is from the Scale2X page where they describe the algorithm (which thankfully was already included in PyGame):
https://www.scale2x.it/algorithm

What do you think?

Thanks for the ideas!

**Comment by MetinSeven** [comment]
I like it. It's a part of the famous test image for pixel interpolation algorithms such as HQ2X and xBRZ. Speaking of which, I'd love to see those added to PyDPainter, particularly [xBRZ](https://sourceforge.net/projects/xbrz/), which is the best non-AI algorithm to upscale pixel art.

**Comment by Sleuthgame** [comment]
That's all clear now. Bravo.
Let's move on.

**Comment by Sleuthgame** [comment]
I use AA fill mode while painting this. Pretty usefull to alias those shapes. Great !
![image](https://github.com/mriale/PyDPainter/assets/130657737/80c51007-09e8-4208-ac28-5d85c81b68e8)
