### ISSUE TITLE
Cursor rendering problem on M1 Mac

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#78]
From @hsk Merge request #77:

https://github.com/mriale/PyDPainter/assets/129693/d7b452a2-56dc-4897-a729-b353f091026f

>I ran it on my M1 Mac and it worked.
>However, the cursor color key was wrong.
>So I specified the color key and it worked.
>Thank you in advance for your help.

**Comment by mriale** [comment]
I'm not sure exactly why patch #77 worked because setting color 0 transparent in a 24-bit color image would make black clear, which didn't happen. I don't really want to add the code as-is because something might break later when they fix that bug in Pygame.

So I made these changes to the `develop` branch:
- Made the `cursors.png` image indexed color instead of being 32-bit (true color with transparency)
- Added same code to make color 0 transparent: `self.cursor_images.set_colorkey(0)`

**Comment by hsk** [comment]
Thank you very much.
I was able to confirm this in the develop branch on M1 Mac.
