### ISSUE TITLE
Coordinates indication request

### ISSUE THREAD

**Issue by MetinSeven** [mriale/PyDPainter#79]
Hi Mark,

I just noticed that the shape / line counter starts counting at 0 like the coordinates, so a square of 10 x 10 pixels is indicated as 9→ 9↑

I find this confusing. Would you agree to change this, so that dragging a square or line will indicate the exact amount of pixels of the square or line? It also worked like this in DPaint.

To be frank, I'd also love to see the screen coordinates to start at 1. I don't know anymore whether this was also the case in DPaint, but I think it's more logical: e.g. in 160 x 160 pixels, the first pixel would be pixel number 1, and the last pixel would be pixel 160, in stead of the current 0 and 159.

If you've got doubts about this, maybe because of possible game developer preference, then I'd love to see a Preferences option to choose between the two coordinate variations, and store that in a user's default settings.

Thanks in advance for considering this.

**Comment by mriale** [comment]
I made the coords options into a sub-menu and added 1-based coordinates:
![image](https://github.com/mriale/PyDPainter/assets/26576606/8648d956-efeb-4e5e-a225-b78841f01e4c)

This is in the `develop` branch now.

**Comment by MetinSeven** [comment]
Many thanks mark, much appreciated!
