### ISSUE TITLE
Color change / Remap

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#80]
hi ! I'm not sure how this function works.

I believe it enable to remap colors after I re-organize colors in Palette. But it appears it behave strangely for my understanding.
Can you check this or explain it to me ?

**Comment by mriale** [comment]
I think it's working. If I load `RaytracedLoRes.iff`:
![Screenshot_20230809_214410](https://github.com/mriale/PyDPainter/assets/26576606/4fa328da-740e-42cc-8184-8f13af9dda77)

If I do default palette:
![Screenshot_20230809_214542](https://github.com/mriale/PyDPainter/assets/26576606/723c661a-5074-49c8-99f0-d1c5ed001cc8)

I get:
![Screenshot_20230809_214630](https://github.com/mriale/PyDPainter/assets/26576606/d514179f-5ea2-4387-b8d2-7671b7346836)

If I do a remap:
![Screenshot_20230809_214654](https://github.com/mriale/PyDPainter/assets/26576606/543fad20-f892-455e-9ed1-d8abbc0a4fc5)

I get:
![Screenshot_20230809_214822](https://github.com/mriale/PyDPainter/assets/26576606/44fd3522-d10d-47c3-8891-fe2a325589b3)
It doesn't cycle like the original, but the image looks as good as it can with the default palette.

Were you expecting different or better functionality? I believe this is close to DPaint III behavior. Is it intuitive according to today's standards? Maybe not.

**Comment by Sleuthgame** [comment]
OK, thanks. I was expecting that, exactly what I remember of Dpaint too. But it does not work if I edit colors in Palette.
I will record a screenshot video, it will be easier to figure out what's happening.

**Comment by Sleuthgame** [comment]
OK, quite simple.
Load this PNG files from PhotoShop. Palette is messy. Shades of grey are not sorted (they are in PNG export but...)
![image](https://github.com/mriale/PyDPainter/assets/130657737/98db77b0-1f49-49e8-b707-952fc1b529d2)
[](url)
![test-AA-4](https://github.com/mriale/PyDPainter/assets/130657737/ebaeaee0-7312-4ee7-ab8a-9d34e9a5da02)

**Comment by Sleuthgame** [comment]
Re-organize colors. One Exchange, one gradient. Picture is now messy.
![image](https://github.com/mriale/PyDPainter/assets/130657737/ffeae644-23ba-46b6-b19c-2a763a6071c4)

**Comment by Sleuthgame** [comment]
Use REMAP. 
!!???
![image](https://github.com/mriale/PyDPainter/assets/130657737/e19a232a-0420-4a1f-9691-6b60d3978cf5)

**Comment by mriale** [comment]
Turns out PyDPainter only backed up the original palette when loading IFF files. Since this was a PNG file, the original palette was never backed up. I changed the code so both are backed up now, and remap works as expected now. Thanks for finding that!
