### ISSUE TITLE
Implement Tint drawmode

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#82]
From DPaint III manual:

**TINT**
Replaces the hue and saturation of the affected pixels with the current color but leaves the value of the screen pixels unaffected. This option is available only with built-in brushes.

**Comment by mriale** [comment]
@Sleuthgame I guess I had forgotten about tint, but it turns out that it wasn't that hard to implement. Thanks for the cool test picture to color:
![Screenshot_20230813_182224](https://github.com/mriale/PyDPainter/assets/26576606/4143e8f7-f7c3-4be6-a849-5a168cae6218)
I put the blue fill color on the stencil so I could just tint the shapes with a big brush.

**Comment by Sleuthgame** [comment]
It look like another legacy usefull tool !

**Comment by Sleuthgame** [comment]
Tested. Work fine ! 
![image](https://github.com/mriale/PyDPainter/assets/130657737/3ba96476-e095-4c46-8ec6-a48630b4f25c)

**Comment by Sleuthgame** [comment]
Hi !

Are we continuing the logic of function key shortcuts for modes with **F9** for **Tint**?
(and **F12** for **AntiAliasing** filling? Or SHIFT-F8 ?)

I'm writing the mode .md manual, that's why I'm asking now. ;-)

**Comment by mriale** [comment]
DPaint used F9 to toggle the menu bar, which I implemented. I never used this shortcut back in the day. I used F10 to toggle all the toolbox and menu bar together. Maybe it would be more useful for F9 to be assigned to Tint.

I've already got the fill modes mapped to numbers:
    SOLID = 0
    TINT = 1
    BRUSH = 2
    WRAP = 3
    PERSPECTIVE = 4
    PATTERN = 5
    VERTICAL = 6
    VERT_FIT = 7
    HORIZONTAL = 8
    HORIZ_FIT = 9
    BOTH_FIT = 10
    ANTIALIAS = 11
    SMOOTH = 12

 I don't have tint or perspective fill modes implemented yet, but we're already up to 13. Not sure how to map those to shift-function keys.

**Comment by Sleuthgame** [comment]
I barely used F9 either. Sure F9 for Tint will be more convenient.

I downloaded the last dev version, but I do not have theses new shortcut yet.

**Comment by Sleuthgame** [comment]
I'm done ! I'll send you an email with mode.md and all pictures needed.

**Comment by mriale** [comment]
@Sleuthgame Awesome documentation! The demo pictures make it so easy to understand! I added it to `develop`.

I think I'm missing `color-examples.png`.

Thanks so much for all the work you put into this guide! I think a lot of people will benefit from this.

**Comment by Sleuthgame** [comment]
Please erase text :
 (in this case red).

Add :
Use this mode as a monochrome ink pad, allowing you to create shadow
effects, offset outlines or color stacking.

https://stephane-anquetil-auteur.com/
CrimeBooks / 404 éd. et CrimeZoom / Aurora Games.


Le mar. 29 août 2023 à 06:09, Mark Riale ***@***.***> a
écrit :

**Comment by Sleuthgame** [comment]
Not a nice picture, but it's hard to understand how to use it.

**Comment by mriale** [comment]
I made a more attractive color draw mode picture:

![color-examples](https://github.com/mriale/PyDPainter/assets/26576606/2c1bb3f6-ceee-4d81-af0b-9fc5ba36b16a)

Hopefully it has enough examples in it.

**Comment by mriale** [comment]
Oh, and I made the Tint draw mode hotkey be `F9`.

**Comment by Sleuthgame** [comment]
Nice. On the path to release ?

We need a .md page tracking all the features we invent that are not DPaint legacy. There a lot now !

**Comment by Sleuthgame** [comment]
Oh, on mode.md all the anchors links to Smear and Cycle Range are erased !
<a name="Smear"></a>
<a name="cyclerange"></a>

It's basic html working on Ghostwriter preview. I do not found another Markdown syntax to do this.

Anyway, cyclerange can be moved to a new palette.md. There is so much to explain about Palette, it won't fit in Picture.
