### ISSUE TITLE
Revert to last save

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#86]
When doing tests, tutorials, I often have to reload my starting picture.

Revert to last save is a great and easy way to do this.

In photoShop, it's "**Revert**" in File menu.

Can be "Revert to last save" or "Reload as saved" in Picture menu of PydPainter.

**Comment by mriale** [comment]
Added Picture/Revert to menu with a shortcut as F12. This is in develop.

**Comment by Sleuthgame** [comment]
Thanks. Not sure about F12. I like F n for mode selection or toolbar/fullscreen display.

**Comment by mriale** [comment]
@Sleuthgame How about ctrl-alt-z like an extended Undo? I was also considering ctrl-shift-z.

**Comment by Sleuthgame** [comment]
Both are fine, can be hold with only left hand. Maybe CTRL-shift-z is easier.

**Comment by mriale** [comment]
I just noticed that redo is both CTRL-shift-z and CTRL-y.

I left revert as CTRL-alt-z.
