### ISSUE TITLE
MultiCycle support

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#88]
Original DPaint Cycle support multicycle. What is it ? Quote from Dpaint manual:
```
Use MultiCycle (in the Prefs menu) to achieve the same effect with a multicolored brush, where
**each color in the brush cycles through its range independently** of the others.
```

![image](https://github.com/mriale/PyDPainter/assets/130657737/8c2d4041-5587-4e20-b0e2-fae2f370a5fe)

_Multicycle simulated on the cocarde_

**Comment by mriale** [comment]
Finally got around to adding MultiCycle support.

**Comment by Sleuthgame** [comment]
That's too much fun, it's dangerous ! 😄 

Consider allowing another brush after use. It's stuck to the brush we use for multicycle, handled from top left. 🚫

**Comment by Sleuthgame** [comment]
Have to uncheck **Multicyle** to free the brush and go back to normal.

**Comment by Sleuthgame** [comment]
Previous behaviour is hard to reproduce. I'll try screen recording.

Another side-effect :
It works nicely with trace (**CTRL**) with ellipse tool. Wonderfull effet.
Do not work with rectangle and circle.
![image](https://github.com/user-attachments/assets/416767cf-555e-44c0-b6e2-7662dc73fdd0)

**Comment by mriale** [comment]
I just played with this on DPaint III, and it looks like I have to work on this a bit more. Depending on which cycle range you select, it works just like regular CYCLE mode where the range of colors is spread once over a line drawn. My current implementation just cycles the brush every time it stamps it so the colors in the range repeat many times over the length of a line.

**Comment by Sleuthgame** [comment]
l like it as you did.

I'm not sure many pixel artists use or even know about this trick. I'll gladly do a video on it, but don't make it a priority or blocking thing.

**Comment by mriale** [comment]
It works like regular cycle now with better support for ranges.

**Comment by mriale** [comment]
I also fixed the weird brush problem when switching between a custom brush and a built-in brush in MultiCycle mode.

**Comment by Sleuthgame** [comment]
Tricky one. Well done.
