### ISSUE TITLE
How to crop an image?

### ISSUE THREAD

**Issue by jnikula** [mriale/PyDPainter#90]
This is pretty nostalgic! :)

I'm wondering how to crop an image. Picture | Page Size... lets me set the page size, but that keeps the portion from top left, and I'd want to choose a different part of the image to keep.

I don't seem to be able to do a round trip via `ilbmtoppm` -> crop ppm -> `ppmtoilbm` either, because those tools modify the order of the colors in the color map, and I need to preserve them. :(

**Comment by mriale** [comment]
Could you grab the part of the image you want as a brush? Then you could clear the screen and stamp it down again.
Alternatively you could save the brush and load it in again as picture.
Does either of those things work for you?

**Comment by jnikula** [comment]
Thanks, that worked! It's just been like, uh, 30 years since I last used Deluxe Paint, so I'm a little rusty. :)
