### ISSUE TITLE
Add basic animation support

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#96]
Add basic support for animation:
* Setting number of frames
* Moving from frame to frame
* Playback
* Loading IFF ANIM
* Saving IFF ANIM

**Comment by mriale** [comment]
Need to make palette into an object so it can be easily be used in animation frames. Currently the palette is stored globally in several variables:
- config.pal - current palette used almost everywhere. This is color skewed to make sure each palette entry is unique and color cycled colors don't get collapsed into the same color.
- config.backuppal - palette storage during color cycling
- config.truepal - true color palette (not color skewed)
- config.loadpal - palette that was loaded from a file

Rather than store the palette with every frame, ranges of frames need to reference keyframe palettes. DPaint V implements this but the GUI for it is not very usable.

**Comment by mriale** [comment]
I want to add an animation toolbar on the bottom of the screen with VCR controls and a slider:

`|< << > >> >| ----------- + - P`

To the right of the slider:
- Add frame
- Remove frame
- Palette key frame indicator

**Comment by mriale** [comment]
Added image but no code yet.

![image](https://github.com/mriale/PyDPainter/assets/26576606/e7c711ef-620b-40e4-b351-16b37c0f511e)

**Comment by hsk** [comment]
Good luck!
