### ISSUE TITLE
Support HAM and 24-bit IFF files

### ISSUE THREAD

**Issue by mriale** [mriale/PyDPainter#97]
Use the default Pygame loader for HAM and 24-bit IFF files. This returns a 24-bit image which is then converted down to an 8-bit image for PyDPainter to use.

**Comment by Sleuthgame** [comment]
Works fine !
If loaded as ANIMATION, add a request to ask if we want fixed palette or not.
If fixed palette, load the first 1/3 frame as reference for palette conversion. Most animation don't show all on first frame. Objets or titles appears later after some fading.

**Comment by Sleuthgame** [comment]
IE: you have a 100 frames animation. Palette on frame 33 or 66 are good samples to create a palette. Palette in frame 1 is 99% chance to be all black.
